sonar.projectKey=rcsilva83_TheDrumGizmoExp
sonar.organization=rcsilva83


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=TheDrumGizmoExp
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude generated coverage HTML files and binary/non-text files from source analysis
sonar.exclusions=tmp-artifacts/**,coverage/**,**/*.png,**/*.mid,**/*.xcf
