# CMake generated Testfile for 
# Source directory: /home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test
# Build directory: /home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(resource "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/resource")
set_tests_properties(resource PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;48;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(audiocache "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/audiocache")
set_tests_properties(audiocache PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;65;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(audiocachefile "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/audiocachefile")
set_tests_properties(audiocachefile PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;86;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(audiocacheidmanager "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/audiocacheidmanager")
set_tests_properties(audiocacheidmanager PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;104;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(audiocacheeventhandler "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/audiocacheeventhandler")
set_tests_properties(audiocacheeventhandler PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;116;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(enginetest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/enginetest")
set_tests_properties(enginetest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;133;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(paintertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/paintertest")
set_tests_properties(paintertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;146;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(configfile "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/configfile")
set_tests_properties(configfile PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;161;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(randomtest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/randomtest")
set_tests_properties(randomtest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;171;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(atomictest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/atomictest")
set_tests_properties(atomictest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;181;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(syncedsettingstest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/syncedsettingstest")
set_tests_properties(syncedsettingstest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;188;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(imagecachetest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/imagecachetest")
set_tests_properties(imagecachetest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;195;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(semaphoretest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/semaphoretest")
set_tests_properties(semaphoretest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;207;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(drumkitcreatortest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/drumkitcreatortest")
set_tests_properties(drumkitcreatortest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;218;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(bytesizeparsertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/bytesizeparsertest")
set_tests_properties(bytesizeparsertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;231;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(notifiertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/notifiertest")
set_tests_properties(notifiertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;237;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(dgxmlparsertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/dgxmlparsertest")
set_tests_properties(dgxmlparsertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;242;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(domloadertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/domloadertest")
set_tests_properties(domloadertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;254;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(configparsertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/configparsertest")
set_tests_properties(configparsertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;265;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(midimapparsertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/midimapparsertest")
set_tests_properties(midimapparsertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;276;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(eventsdstest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/eventsdstest")
set_tests_properties(eventsdstest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;288;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(powermaptest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/powermaptest")
set_tests_properties(powermaptest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;294;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(midimappertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build-cmake-ci/test/midimappertest")
set_tests_properties(midimappertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;300;dg_add_uunit_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
