# CMake generated Testfile for 
# Source directory: /home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test
# Build directory: /home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(audiocache "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/audiocache")
set_tests_properties(audiocache PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;65;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(audiocachefile "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/audiocachefile")
set_tests_properties(audiocachefile PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;87;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(audiocacheidmanager "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/audiocacheidmanager")
set_tests_properties(audiocacheidmanager PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;105;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(audiocacheeventhandler "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/audiocacheeventhandler")
set_tests_properties(audiocacheeventhandler PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;117;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(framesizetest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/framesizetest")
set_tests_properties(framesizetest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;137;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(enginetest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/enginetest")
set_tests_properties(enginetest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;156;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(configfile "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/configfile")
set_tests_properties(configfile PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;186;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(randomtest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/randomtest")
set_tests_properties(randomtest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;196;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(sampleselectiontest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/sampleselectiontest")
set_tests_properties(sampleselectiontest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;206;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(atomictest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/atomictest")
set_tests_properties(atomictest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;222;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(syncedsettingstest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/syncedsettingstest")
set_tests_properties(syncedsettingstest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;229;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(semaphoretest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/semaphoretest")
set_tests_properties(semaphoretest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;250;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(drumkitcreatortest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/drumkitcreatortest")
set_tests_properties(drumkitcreatortest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;261;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(bytesizeparsertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/bytesizeparsertest")
set_tests_properties(bytesizeparsertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;274;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(notifiertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/notifiertest")
set_tests_properties(notifiertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;280;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(dgxmlparsertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/dgxmlparsertest")
set_tests_properties(dgxmlparsertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;285;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(domloadertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/domloadertest")
set_tests_properties(domloadertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;297;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(configparsertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/configparsertest")
set_tests_properties(configparsertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;308;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(midimapparsertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/midimapparsertest")
set_tests_properties(midimapparsertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;319;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(eventsdstest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/eventsdstest")
set_tests_properties(eventsdstest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;331;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(powermaptest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/powermaptest")
set_tests_properties(powermaptest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;339;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(inputfilterstest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/inputfilterstest")
set_tests_properties(inputfilterstest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;345;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(versionstrtest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/versionstrtest")
set_tests_properties(versionstrtest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;360;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(directorytest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/directorytest")
set_tests_properties(directorytest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;371;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(midimappertest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/midimappertest")
set_tests_properties(midimappertest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;382;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(audioinputenginemiditest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/audioinputenginemiditest")
set_tests_properties(audioinputenginemiditest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;394;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(colourtest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/colourtest")
set_tests_properties(colourtest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;420;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(utf8test "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/utf8test")
set_tests_properties(utf8test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;430;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
add_test(drumgizmoclitest "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/build2/test/drumgizmoclitest")
set_tests_properties(drumgizmoclitest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;41;add_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;470;dg_add_doctest_test;/home/runner/work/TheDrumGizmoExp/TheDrumGizmoExp/test/CMakeLists.txt;0;")
