#!/usr/bin/env python3
"""
Generate a prioritized file-gap report from gcovr JSON summary output.

The report focuses on uncovered branch counts to highlight where additional
tests can reduce the biggest behavioral risk.

Usage:
    python3 scripts/generate-coverage-gap-report.py \
        --summary coverage-summary.json \
        --output docs/coverage-top20-file-gaps.md
"""

import argparse
import json
import os
from datetime import datetime, timezone


def ceil_to_step(value, step):
    return ((value + step - 1) // step) * step


def target_percent(current_percent, min_floor, max_cap, step, uplift):
    target = ceil_to_step(int(current_percent) + uplift, step)
    target = max(min_floor, target)
    target = min(max_cap, target)
    return target


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate top uncovered-files report with branch gaps"
    )
    parser.add_argument(
        "--summary",
        default="coverage-summary.json",
        help="Path to gcovr --json-summary output (default: coverage-summary.json)",
    )
    parser.add_argument(
        "--output",
        default="docs/coverage-top20-file-gaps.md",
        help=(
            "Path to output markdown report "
            "(default: docs/coverage-top20-file-gaps.md)"
        ),
    )
    parser.add_argument(
        "--max-files",
        type=int,
        default=20,
        help="Maximum number of prioritized files (default: 20)",
    )
    parser.add_argument(
        "--exclude-prefix",
        action="append",
        default=["test/"],
        help="Exclude files with this path prefix (repeatable, default: test/)",
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)

    with open(args.summary, encoding="utf-8") as fh:
        payload = json.load(fh)

    rows = []
    for file_entry in payload.get("files", []):
        filename = file_entry.get("filename", "")
        if not filename:
            continue

        if any(filename.startswith(prefix) for prefix in args.exclude_prefix):
            continue

        branch_total = int(file_entry.get("branch_total") or 0)
        branch_covered = int(file_entry.get("branch_covered") or 0)
        line_total = int(file_entry.get("line_total") or 0)
        line_covered = int(file_entry.get("line_covered") or 0)

        if branch_total <= 0:
            continue

        uncovered_branches = branch_total - branch_covered
        uncovered_lines = line_total - line_covered

        branch_percent = (
            (branch_covered / branch_total) * 100.0 if branch_total > 0 else 0.0
        )
        line_percent = (line_covered / line_total) * 100.0 if line_total > 0 else 0.0

        rows.append(
            {
                "filename": filename,
                "branch_total": branch_total,
                "branch_covered": branch_covered,
                "branch_percent": branch_percent,
                "uncovered_branches": uncovered_branches,
                "line_total": line_total,
                "line_covered": line_covered,
                "line_percent": line_percent,
                "uncovered_lines": uncovered_lines,
            }
        )

    rows.sort(
        key=lambda row: (
            -row["uncovered_branches"],
            -row["uncovered_lines"],
            row["filename"],
        )
    )
    top_rows = rows[: args.max_files]

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    report_lines = [
        f"# Coverage Gap Hotspots (Top {args.max_files})",
        "",
        "This file is generated by `scripts/generate-coverage-gap-report.py`.",
        "Prioritization is sorted by uncovered branch count (descending), then",
        "uncovered line count.",
        "",
        f"- Source summary: `{args.summary}`",
        f"- Generated at (UTC): `{generated_at}`",
        f"- Excluded prefixes: {', '.join(f'`{p}`' for p in args.exclude_prefix)}",
        "",
        "| Rank | File | Uncovered branches | Branches (cov/total) | Branch % | Uncovered lines | Lines (cov/total) | Line % | Branch target | Line target |",
        "| ---: | ---- | -----------------: | --------------------: | -------: | --------------: | ----------------: | -----: | ------------: | ---------: |",
    ]

    for index, row in enumerate(top_rows, start=1):
        branch_target = target_percent(
            current_percent=row["branch_percent"],
            min_floor=40,
            max_cap=90,
            step=5,
            uplift=20,
        )
        line_target = target_percent(
            current_percent=row["line_percent"],
            min_floor=60,
            max_cap=95,
            step=5,
            uplift=20,
        )

        report_lines.append(
            "| "
            + f"{index} | `{row['filename']}` | {row['uncovered_branches']} | "
            + f"{row['branch_covered']} / {row['branch_total']} | "
            + f"{row['branch_percent']:.1f}% | {row['uncovered_lines']} | "
            + f"{row['line_covered']} / {row['line_total']} | "
            + f"{row['line_percent']:.1f}% | "
            + f"{branch_target}% | {line_target}% |"
        )

    if not top_rows:
        report_lines.append("| - | _(no matching files)_ | 0 | 0 / 0 | 0.0% | 0 | 0 / 0 | 0.0% | 0% | 0% |")

    output_dir = os.path.dirname(args.output)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write("\n".join(report_lines) + "\n")

    summary_path = os.environ.get("GITHUB_STEP_SUMMARY", "")
    if summary_path:
        with open(summary_path, "a", encoding="utf-8") as fh:
            fh.write("## Top uncovered files by branch gaps\n\n")
            fh.write("| Rank | File | Uncovered branches | Branch % | Branch target |\n")
            fh.write("| ---: | ---- | -----------------: | -------: | ------------: |\n")
            for index, row in enumerate(top_rows, start=1):
                branch_target = target_percent(
                    current_percent=row["branch_percent"],
                    min_floor=40,
                    max_cap=90,
                    step=5,
                    uplift=20,
                )
                fh.write(
                    f"| {index} | `{row['filename']}` | {row['uncovered_branches']} "
                    f"| {row['branch_percent']:.1f}% | {branch_target}% |\n"
                )
            fh.write(
                "\nDetailed line and branch targets are published in "
                f"`{args.output}` and the `coverage-reports` artifact.\n"
            )

    print(f"Wrote prioritized file-gap report to {args.output}")


if __name__ == "__main__":
    main()
